### ISSUE TITLE
Привести airtables в порядок.

### ISSUE THREAD

**Issue by bmsdave** [piterjs/piterjs#2]
@nin-jin  тебя какие поля интересуют? Что в порядок приводить?

**Comment by nin-jin** [comment]
Events:
- Date from
- Event number
- Place *
- Speeches

Speeches:
- Description
- Name
- Slides
- Speakers
- Запись *

Speakers:
- Company & position *
- Name
- Notes
- Photo

Звёздочкой пометил то, что пока не выводится, но тоже потребуется.

**Comment by fogrew** [comment]
Актуализировал всё от 30 до 34 митапа. Работаем дальше.

**Comment by nin-jin** [comment]
Закрываю так как от Airtable отказываемся. Думаю у нас так и не дойдут руки до 1-30 митапа. Давайте хотя бы готовить информацию по грядущему митапу.
