### ISSUE TITLE
Заменить хэширование ссылок на ЧПУ

### ISSUE THREAD

**Issue by fogrew** [piterjs/piterjs#4]
Ссылки вида `/piterjs.org/#meetup=recFozG59OIwJiUWU/speech=recBGOpc1gUL6jjQW` - это полный ад.
Хочется, чтобы ссылки были человеко-читабельными.
Вот такие вижу варианты:
* `/34/gerasimov/` - номер митапа и фамилия спикера
* `/2019/02/gerasimov` - год, месяц и фамилия спикера
* `/34/02` - номер митапа, номер доклада
* `/2019/02/02` - год, месяц, номер доклада

Именно фамилия, а не название доклада, потому что правильная транслитерация названий докладов - это боль. Будет неудобно вводить на телефоне длинные названия, а фамилию - ещё куда ни шло.

Описывать ссылку подобно get параметрам лично мне кажется неудобным. Да, можно менять их порядок, но ссылка от того короче не становится.

**Comment by nin-jin** [comment]
Сделаем колонку с правильной транслитерацией?

**Comment by nin-jin** [comment]
> Будет неудобно вводить на телефоне длинные названия, а фамилию - ещё куда ни шло.

Это что за сценарий, где надо вводить ссылку на доклад вручную да ещё и с телефона?

**Comment by nin-jin** [comment]
Вообще, ссылка - техническая деталь, которую редко видят и ещё реже на неё смотрят. Особенно в случае приложения, когда даже строка адреса не показывается.

Я вижу следующие сценарии, где имеет значение вид ссылки:

- Передача её кому-то сообщением. Тут важно скорее, чтобы она была более-менее короткой, а не на 10 строк. Не обязательно прям ультракороткой, то есть каждый символ экономить нет смысла.
- Хакинг путём прямого ввода, но тут надо понимать что какой параметр означает, и тут как раз форма ключ-значение лучше.

**Comment by fogrew** [comment]
В целом можно и ключ=значение оставить, лишь бы было очевидно, как путём подмены ссылки перейти в другое место. Меня только хэши напрягают.

> Сделаем колонку с правильной транслитерацией?

Это как раз сделает ссылки длинными и не читаемыми. К тому же не хочется грузить airtable служебной информацией, нужной для сайта, а не для управления нами контентом. К тому же это усложнит добавление нового контента.

---

Сценарии ввода ссылок существуют

В зале:
— Докладчик быстро перелистывает слайды
— С задних рядов не видно, а пересесть ближе стесняются. Или сидят специально там, чтобы шептаться с друзьями, но не хотят сильно мешать остальным.
— Слайды плохие, код на слайдах не видно - отсвечивает
— Отошли в туалет или ещё куда и не могут вернуться в контекст доклада

Не в зале:
— Знаешь ссылку на один доклад, но хочешь по-быстрому открыть соседний
— Знаешь, как строится ссылка, хочешь сразу без открытия сайта открыть нужный доклад

**Comment by nin-jin** [comment]
> Меня только хэши напрягают.

Диез разделает параметры приложения от расположения, что позволяет браузеру адекватно кешировать и не лазить на сервак лишний раз.

> В зале:

Для этого в приложении должен быть экран "онлайн", где будет отображаться информация по текущей активности. В частности - текущий доклад. Посетитель открывает приложение и он уже там где нужно, ничего дополнительно не вводя.

> Знаешь ссылку на один доклад, но хочешь по-быстрому открыть соседний

Так список докладов рядом - достаточно закрыть текущий.

> Знаешь, как строится ссылка, хочешь сразу без открытия сайта открыть нужный доклад

Быстрее же кликнуть пару раз, чем пытаться угадать каким по счёту был доклад или как правильно пишется имя докладчика.

**Comment by fogrew** [comment]
> Диез разделает параметры приложения от расположения, что позволяет браузеру адекватно кешировать и не лазить на сервак лишний раз.

Под хэшами я имею ввиду не диез, а нечитаемые идентификаторы митапов типа `meetup=recE2oJaecdLIRbCS`

По остальным пунктам я готов согласиться. Действительно: если использовать только сайт как входную точку, то кликание на сайте быстрее и удобнее. И прорабатывать другие пути незачем.

**Comment by nin-jin** [comment]
А, это в airtable такие весёлые идентификаторы.

**Comment by fogrew** [comment]
Вот именно их я предлагаю людям не показывать, а показывать вместо них читабельные идентификаторы. Митап очевидно проще всего по номеру определять, а вот доклады - хз. Мне кажется, проще будет правильно переводить фамилии, чем названия докладов.

Или вовсе порядковый номер доклада использовать. Но с порядковым номером тоже не всё так гладко. Иногда доклады меняются местами, если докладчик опаздывает или если что-то случается.

**Comment by nin-jin** [comment]
Сделал урлы вида: `#meetup=31/speech=9CO`

**Comment by fogrew** [comment]
Мне нравится, теперь прям хорошо! Спасибо!
Лучшей идеи для id докладов у меня нет. Если у кого-нибудь появятся - открывайте ишью.
