### ISSUE TITLE
Обрезать фотографии до квадрата

### ISSUE THREAD

**Issue by fogrew** [piterjs/piterjs#5]
В анонсах мы размещаем квадратные фотографии в стилизованных рамках. Хочется, чтобы на сайте было также. Тогда можно будет установить фиксированные ширину и высоту, чтобы интерфейс не дёргался при подгрузке фоток. Ещё они довольно долго подгружаются из airtable. Поэтому предлагаю поставить наш логотип фоном. Даже если они вообще не загрузятся (вдруг api airtable откажет), на месте фотки будет что-то.

**Comment by nin-jin** [comment]
Алгоритмически сложно определять какую часть можно обрезать,  а какую нет. Тут лучше изначально все фотографии иметь квадратные.

**Comment by fogrew** [comment]
Да, согласен. Лучше изначально квадратные. Заводить ещё одно поле под это не хочется, потому что в нашем airtable аккаунте есть ограничение по загружаемым файлам. Возможно, стоит рассмотреть ещё варианты, где хранить аватарки?

**Comment by nin-jin** [comment]
Почему бы в том же поле и не сохранять все фото квадратными?

Не знаю, я бы вообще всё на гитхабе хранил :-)

Идеально, конечно, своё АПИ запилить, давно хочу сделать, но руки не доходят. Но это в любом случае не быстрый процесс.

**Comment by nin-jin** [comment]
Готово, всё картинки по умолчанию квадратные, не скачут и имеют фолбэк в виде блёклого логотипа.

**Comment by fogrew** [comment]
Теперь ничего не дёргается. Выглядит хорошо. Спасибо!
